# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      # Linting
      - /gitlab-templates/json-validation.yml
      - /gitlab-templates/xml-lint.yml
      - /gitlab-templates/yaml-lint.yml
      # Build
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/freebsd-qt6.yml
      - /gitlab-templates/windows-qt6.yml
